# Generated by Django 4.0.5 on 2022-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='firmname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
