# Generated by Django 4.0.5 on 2022-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0004_enterp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterp',
            name='image',
            field=models.ImageField(default='1920_1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='investor',
            name='image',
            field=models.ImageField(default='1920_1.jpg', upload_to=''),
        ),
    ]
