# Generated by Django 4.0.5 on 2022-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0005_enterp_image_investor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterp',
            name='image',
            field=models.ImageField(default='1920-1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='investor',
            name='image',
            field=models.ImageField(default='1920-1.jpg', upload_to=''),
        ),
    ]
