# Generated by Django 4.0.5 on 2022-08-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0006_alter_enterp_image_alter_investor_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterp',
            old_name='onldesc',
            new_name='bplan',
        ),
    ]
