# Generated by Django 4.0.5 on 2022-08-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0007_rename_onldesc_enterp_bplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
    ]
