# Generated by Django 4.0.5 on 2022-08-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0009_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='forfield',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
