# Generated by Django 4.0.5 on 2022-08-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0010_forum_forfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(default='1920-1.jpg', upload_to=''),
        ),
    ]
