# Generated by Django 4.0.5 on 2022-08-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0011_forum_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
    ]
