# Generated by Django 4.0.5 on 2022-08-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0012_remove_forum_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderuname', models.CharField(default='', max_length=50)),
                ('recieveruname', models.CharField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
