# Generated by Django 4.0.5 on 2022-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0014_alter_comments_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterp',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
    ]
