# Generated by Django 4.0.5 on 2022-08-27 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0015_enterp_is_investor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment',
        ),
    ]
