# Generated by Django 4.0.5 on 2022-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0016_rename_content_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='postid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
