# Generated by Django 4.0.5 on 2022-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0017_comments_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='postid',
            field=models.IntegerField(default='', max_length=100),
        ),
    ]
