# Generated by Django 4.0.5 on 2022-08-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testx', '0018_alter_comments_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='postid',
            field=models.IntegerField(default=''),
        ),
    ]
